### ISSUE TITLE
Error while running example/python3 example.py

### ISSUE THREAD

**Issue by rrmte** [NVIDIA-AI-IOT/jetson-multicamera-pipelines#6]
After following the steps in readme, and trying to run the python3 example.py, error .Please support.

System: Jetson Xavier AGX, with Jetpack 4.5.1

`self._p.send_event(Gst.Event.new_eos())
AttributeError: 'CameraPipelineDNN' object has no attribute '_p'
`

**Comment by ADSFAaron** [comment]
I got the similar error at Jetson Xavier NX developer kit with Jetpack 5.1.1 and python 3.8.10
Did someone have a solution to fix this problem???

The output below is using `deepstream-app --version-all`

```
deepstream-app version 6.1.1
DeepStreamSDK 6.1.1
CUDA Driver Version: 11.4
CUDA Runtime Version: 11.4
TensorRT Version: 8.5
cuDNN Version: 8.6
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keynvbufsurftransform: Could not get EGL display connection
libNVWarp360 Version: 2.0.1d3
```

I've execute `python3 -tt example-no-ai.py` in folder `jetson-multicamera-pipelines/examples`

And got this error

```
Traceback (most recent call last):
  File "example-no-ai.py", line 7, in <module>
    p = CameraPipeline([0, 1])
  File "/home/user/.local/lib/python3.8/site-packages/jetmulticam/pipelines/multicam.py", line 62, in __init__
    os.makedirs(self._logdir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/nx'
Exception ignored in: <function BasePipeline.__del__ at 0xffff8d6f2670>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/jetmulticam/pipelines/basepipeline.py", line 38, in __del__
    self.stop()
  File "/home/user/.local/lib/python3.8/site-packages/jetmulticam/pipelines/basepipeline.py", line 41, in stop
    self._p.send_event(Gst.Event.new_eos())
AttributeError: 'CameraPipeline' object has no attribute '_p
```
